"""Initial migration

Revision ID: 28161d746bb1
Revises: 
Create Date: 2024-09-02 16:23:17.645883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28161d746bb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
