"""Add shared file model

Revision ID: 4a6aa0985c97
Revises: d1d5188437b1
Create Date: 2024-09-02 16:45:48.850222

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4a6aa0985c97'
down_revision = 'd1d5188437b1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('file_path', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        
        # Add the new foreign key constraint with a name
        batch_op.create_foreign_key(
            'fk_shared_file_recipient_id_user',  # constraint name
            'user', ['recipient_id'], ['id']
        )

        # Drop columns that are no longer needed
        batch_op.drop_column('private_key')
        batch_op.drop_column('date_shared')
        batch_op.drop_column('shared_with')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        # Add columns back that were dropped
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shared_with', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_shared', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('private_key', sa.String(length=60), nullable=False))
    
        # Re-create the foreign key constraint on 'owner_id' with a name
        batch_op.create_foreign_key(
            'fk_shared_file_owner_id_user',  # constraint name
            'user', ['owner_id'], ['id']
        )

        # Drop columns that were added in the upgrade
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
