"""Add decryption_key column to SharedFile

Revision ID: a80c0e817b7d
Revises: 4a6aa0985c97
Create Date: 2024-09-04 00:49:33.027183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80c0e817b7d'
down_revision = '4a6aa0985c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decryption_key', sa.String(length=100), nullable=False, server_default='default_value'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_file', schema=None) as batch_op:
        batch_op.drop_column('decryption_key')

    # ### end Alembic commands ###
